#Enable Plugin Metrics???
metrics: true

#Enable Automatic Updater???
updater: true

#Enable mcstats??? (Request data from mojang servers)
mcstats: true

#Disabled Commands
disabledcommands:
- command
- anothercommand

#Language of the plugin (See language folder)
#You can add a custom one by creating a new file and put the name of the file here.
Language: EN

Teleport:
  #Enable delay?
  EnableDelay: false
  #Delay in seconds?
  Delay: 5
Timber:
  #Enable timber?
  Enable: false
  #Destroy leaves too? (Drops loot)
  Leaves: true
  #Take all durability of the logs from the axe?
  AllDurability: true
  #Do you need to have an axe in your hand to use Timber?
  NeedAxe: true
#Repair mode? (If true your items never take damage)
RepairMode: false
#Feed mode? (If true you toggle your feed)
FeedMode: false
#Smite damage and fire?
SmiteDamage: true
#Disable respawn screen?
AutoRespawn: false
#GTool enabled? This is a tool that log blockchanges.
gtool: true
#May you move when you are jailed?
jailmove: false
#Dynmap support (Nothing happens without Dynmap)
Dynmap:
  enable: false
  #Show warps?
  warps: true
  #Warps that are not shown, you can even use world:someworld to show no warps in that world.
  hiddenwarps: ['hiddenwarp1', 'hiddenwarp2', 'world:hiddenworld']

Afk:
  Enabled: true
  #Seconds, minimal 10 seconds
  AfkTime: 180
  KickEnabled: true
  #Seconds, minimal 20 seconds
  KickTime: 300
Bleed:
  #Enable bleed?
  Enabled: false
  #Players only?
  PlayersOnly: false
  
Autosave:
  enabled: true
  time: 300
  message: false
Chat:
  #Enable the custom chat of Ultimate Core? If false Filters are still enabled!
  EnableCustomChat: true
  
  #What is the format?
  #+Group = Group name (If vault installed, else empty)
  #+Prefix = Group prefix (If vault installed, else empty)
  #+Suffix = Group suffix (If vault installed, else empty)
  #+Name = Raw name
  #+Displayname = Displayname [WARNING: Some plugins automaticly set the rank/faction/etc before the players displayname]
  #+World = Current World name
  #+WorldAlias = First letter of the worlds name
  #+Message = Message the player is trying to send
  #Color codes supported!
  Format: '&6+Prefix&6+Displayname: &r+Suffix+Message'
  
  #Group formats: [REQUIRES VAULT + PERMISSION PLUGIN] 	
  #Every group that is not registered here uses the Global format
  Groups:
    Enabled: false
    #+Name = Raw name
    #+Displayname = Nick name
    #+World = Current World name
    #+WorldAlias = First letter of the worlds name
    #+Message = Message the player is trying to send
    #Color codes supported!
    #GROUP NAMES ARE CASE SENSITIVE!!!
    Player: '&9[&6Player&9] &6+Displayname: &f+Message'
    Admin: '&6[&4Admin&6] &6+Displayname: &f+Message'
  Tab:
    Enabled: false
    #Groups tab prefixes
    #Watchout! Too long prefixes can short player names for some characters
    #GROUP NAMES ARE CASE SENSITIVE!!!
    Player: '&6'
    Admin: '&4'
  #Enable spam/swear/etc filter?
  SpamFilter: true
  SwearFilter: false
  RepeatFilter: true
  CapsFilter: true
  UrlFilter: true
  IpFilter: true
  
  #Default message(Command) colors
  Default1: '&3'
  Default2: '&b'
  
  #Colors chat(Chat) (Used for /say, /msg etc)
  Color1: '&6'
  Color2: '&e'
  
MuteBlockedCmds:
  - '/msg'
  - '/w'
  - '/r'
  - '/mail'
  - '/m'
  - '/whisper'
  - '/tell'
  - '/er'
  - '/reply'
  - '/ereply'
  - '/email'
  - '/etell'
  - '/ewhisper'
  - '/pm'
  - '/mute'
SwearWords:
  - 'fuck'
  - 'fuk'
  - 'fok'
  - 'fock'
  - 'noob'
  - 'n00b'
  - 'noeb'
  - 'ass'
  - 'anus'
  - 'poop'
  - 'dick'
  - 'slut'
  - 'shit'
  - 'cancer'
  
Explode:
  #Disable explosions??? (True = disabled)
  Creeper: false
  TNT: false
  Ghast: false
  Enderdragon: false
  Wither: false
  Lightning: false
Weather:
  #Disable rain? (True = Disabled)
  Rain: false
Tp:
  TpaCancelDelay: 30
messages:
  #Will messages been shown in the bossbar?
  enabledbossbar: false
  #Will messages been shown in the chat?
  enabledchat: false
  #Randomise the messages?
  randomise: true
  #The time between each message
  time: 60
  #Decrease: Will the bars health descrease until the next message shows?
  decrease: true
  #USE messages.txt TO CHANGE THE MESSAGES!