#Enable Automatic Updater?
Updater:
  #Check for updates? (Set to false to totaly disable the Updater (And /uc update))
  check: true
  #Download the updates automaticly? (When disabled you can still use /uc update to download)
  download: false
#Enable Pugin Metrics (MCstats.org)
Metrics: true
#Allow this plugin to connect to the mojang servers?
Mojang: true
#When UC runs into an error, do you want it to automatically send it to the ultimatecore team?
ErrorSend: true
#Language of the plugin (See Messages folder)
#You can add a custom one by creating a new file and put the name of the file here.
Language: EN

Afk:
  #Is the afk system enabled?
  Enabled: true
  #How long does it take before someone is marked as afk? (In seconds)
  AfkTime: 180
  #Kick players when they are afk for too long? (In seconds)
  KickEnabled: true
  #How long does it take before someone is kicked for being inactive? (In seconds) (Including the time before the player was marked as afk)
  KickTime: 900

#Enable instant respawning?
InstantRespawn: false

Blood:
  #Enable blood?
  Enabled: false
  #Enable it for players only?
  PlayersOnly: false

#Dynmap support (Nothing happens without Dynmap)
Dynmap:
  Enable: true
  #Show warps?
  Warps: true
  #Warps that are not shown, you can even use world:someworld to show no warps in that world.
  Hiddenwarps:
  - hiddenwarp1
  - hiddenwarp2
  - hiddenwarp3

Economy:
  #Enable the ultimatecore economy?
  #When disabled, another economy plugin must be enabled or ultimatecore may have problems.
  enabled: true
  #How is the money amount displayed?
  #Use %Amount for the value
  format: "$%Amount"
  #What is the currency name? (Used for Vault compatibility)
  currencyName: "dollar"
  #What is the currency name in plural? (Also used for Vault compatibility)
  currencyNamePlural: "dollars"
  #How much money does a player start with after joining the server?
  startingBalance: 10.0
  #Round balances on a certain number of decimals. (-1 for no rounding)
  roundBalance: 3
  #The minimum amount of money a player can have.
  #This value is only used in setting and withdrawing money in UltimateCore, other plugins and the pay command use 0 as minumum.
  minimumMoney: 0
  #The maximum amount of money a player can have. (-1 for infinite)
  maximumMoney: -1

Explode:
  #Disable explosions? (True = disabled)
  Creeper: false
  TNT: false
  Ghast: false
  Enderdragon: false
  Wither: false
  Lightning: false

Messages:
  #Are the messages shown in the chat?
  Enabledchat: false
  #Are the messages shown in the bossbar?
  Enabledbossbar: false
  #Are the messages shown in the action bar?
  Enabledactionbar: false
  #Show the messages in a random order?
  Randomise: false
  #The time until the next message is shown (In seconds)
  Time: 120
  #(Only for the bossbar) Let the bossbar decrease until the next message?
  Decrease: true
  #(Only for the bossbar) How long should the message stay?
  Stay: 30
  #(Only for the bossbar) The color of the bar under the message?
  #Options: YELLOW, BLUE, GREEN, PINK, PURPLE, RED, WHITE
  Color: GREEN
  #(Only for the bossbar) The style of the bar under the message?
  #Options: SOLID, SEGMENTED_6, SEGMENTED_10, SEGMENTED_12, SEGMENTED_20
  Style: SOLID
  #Use messages.txt to change the messages.

Autosave:
  #Enable autosaving?
  Enabled: false
  #Show a message each autosave?
  Message: false
  #The time between each autosave. (In seconds)
  Time: 300

Timber:
  #Enable timber?
  Enable: false
  #Destroy leaves too? (Drops loot)
  Leaves: true
  #Take all durability of the logs from the axe?
  AllDurability: true
  #Do you need to have an axe in your hand to use Timber?
  NeedAxe: true

Weather:
  #Disable rain and thunder? (True = Disabled)
  Rain: false

#To change the motd, just use the motd in the server.properties
Motd:
  #Enable replacing color codes like &6 by their color
  EnableColors: true
  #Enable replacing variables like +Player
  #All variables:
  # +Player        (Player's name)
  # +Ip            (Player's ip)
  # +Money         (The amount of money the player has)
  # +Version       (Minecraft version)
  # +Maxplayers    (Max players for the server)
  # +Onlineplayers (Amount of players online on the server)
  # +Servername    (The name of the server set in the server.properties)
  EnableVariables: true
  #Enable ban motds?
  #This will show a custom motd to the player if the player is banned.
  EnableBanMotd: true
  #This is the custom motd which is shown if a player is banned.
  #Use /n for new line
  #All variables:
  # +Bantime     (How long until the player is unbanned)
  # +Banreason   (Why the player was banned)
  # +All the variables named at EnableVariables
  BanMotd: "&4&lYou are banned! &c(+Bantime left)\n&4&lReason: &c+Banreason"

#Enable broadcasting when the mojang servers are offline?
MojangServersBroadcasting: true

#How much delay should the mojang server checker have?
#Recommended between 30 seconds and 150 seconds
MojangServersDelay: 90

#Are join and leave messages visible?
JoinLeaveVisible: true

#Teleport all players to the spawn after they join?
SpawnOnJoin: false

#Chat customization
Chat:
  #How is the /alert command displayed?
  AlertFormat: "&0[&4&lALERT&0] @2%Message"
  #How is the /broadcast command displayed?
  BroadcastFormat: "&6[&e&lBROADCAST&6] @2%Message"
  #How is the /me command displayed?
  MeFormat: "&7* %Player %Message"
  #How is the /msg command displayed?
  MsgFormat: "@1[@2%Player1 @1-> @2%Player2@1] &e%Message"
  #How is the /msg command displayed for spies?
  MsgFormatSpy: "&7[&f%Player1 &7-> &f%Player2&7] &f%Message"
  #How is the /say command displayed?
  SayFormat: "&5[&d%Player&5] %Message"
  #How is the /ask command displayed?
  AskFormat: "@1%Player asked: &e%Message"
  #How is the /answer command displayed?
  AnswerFormat: "@1%Player answered: &e%Message"
  #How is the /adminchat command displayed?
  AdminchatFormat: "&4[&cAdminChat&4] &1@1%Player: &e%Message"

  #The UltimateCore message colors
  #A link of all chatcolors, enter them without the '&':
  #http://ultimatecore.ga/faq/3
  #[@1] The default UltimateCore message color (Default = Dark aqua)
  Default: 3
  #[@2] The message color for values, like player names (Default = aqua)
  Value: b
  #[@3] The message color when there is a problem, like too less arguments (Default = red)
  Error: c

  #Enable the custom chat of UltimateCore? If false Filters are still enabled!
  EnableCustomChat: true
  #Disable/enable Ultimatecore deathmessages. true = enabled, false = disabled.
  EnableCustomDeathmessages: true

  #What is the format?
  # +Group         (Group name (If vault installed, else empty))
  # +Prefix        (Group prefix (If vault installed, else empty))
  # +Suffix        (Group suffix (If vault installed, else empty))
  # +Name          (Raw name)
  # +Displayname   (Displayname [Gets replaced by nick, if available])
  # +World         (Current World name)
  # +WorldAlias    (First letter of the worlds name)
  # +Message       (Message the player is trying to send)
  # +Town          (The town the player is in (Towny))
  # +Faction       (The faction the player is in (Factions))
  # +Ip            (Player's ip)
  # +Money         (The amount of money the player has)
  # +Version       (Minecraft version)
  # +Maxplayers    (Max players for the server)
  # +Onlineplayers (Amount of players online on the server)
  # +Servername    (The name of the server set in the server.properties)
  # +Uptime        (How long the server has been online)
  #Color codes supported!
  Format: '&6+Prefix&6+Displayname: &r+Suffix+Message'

  #Group formats: [REQUIRES VAULT + PERMISSION PLUGIN]
  #Every group that is not registered here uses the Global format
  Groups:
    Enabled: false
    #Color codes supported!
    #(All the values named above will work here too)
    #GROUP NAMES ARE CASE SENSITIVE!!!
    Player: '&9[&6Player&9] &6+Displayname: &f+Message'
    Admin: '&6[&4Admin&6] &6+Displayname: &f+Message'
  Tab:
    #Are tab prefixes enabled?
    Enabled: true
    #The default tab format
    #(All the values named above will work here too)
    DefaultFormat: '&e+Displayname'
    #Groups tab formats
    #(All the values named above will work here too)
    #GROUP NAMES ARE CASE SENSITIVE!!!
    Groups:
      Player: '&e+Displayname'
      Admin: '&6+Displayname'
    #Will be added after the name of an afk player
    #+Original will be replaced with what the tab name was without the afk tag
    AfkFormat: '+Original &c[AFK]'
    #Custom header and footer
    #(All the values named above will work here too)
    HeaderFooterEnabled: false
    Header:
    - "&bWelcome to this server, +Displayname!"
    - "&6Players online: +Onlineplayers/+Maxplayers"
    Footer:
    - "&cChange this message in the UltimateCore config.yml"
  Nametag:
    #Is changing nametags enabled?
    Enabled: false
    #The default prefix
    DefaultPrefix: "&e"
    #The default suffix
    DefaultSuffix: ""
    #Group nametag prefixes & suffixes
    #(All the values named above will work here too)
    #GROUP NAMES ARE CASE SENSITIVE!!!
    Groups:
      Player:
        Prefix: "&6[&ePlayer&6] &e"
        Suffix: ""
      Admin:
        Prefix: "&4[&cAdmin&4] &e"
        Suffix: ""
  #Enable spam/swear/etc filter?
  SpamFilter: true
  SwearFilter: false
  RepeatFilter: true
  CapsFilter: true
  UrlFilter: true
  IpFilter: true

#Command customization
Command:
  #Disabled commands
  DisabledCommands:
  - Example_Command
  #Enable the custom unknown command message? (Customizable in messages file)
  UnknownCommand: true
  #Broadcast when someone gets banned?
  BanBroadcast: true
  #Remove positive effects when being healed?
  HealPositive: false
  #Home limits for permissions. Default limit is 1
  HomeLimits:
    #Player with uc.sethome.member has 2 homes
    member: 2
    #Player with uc.sethome.vip has 5 homes
    vip: 5
    #Player with uc.sethome.unlimited has infinite homes
  Jail:
    #Allow jailed players to move?
    move: true
    #Allow jailed players to talk?
    talk: true
    #Teleport players to the spawn when unjailed?
    spawn: true
  Save:
    #Show autosave messages?
    autosaveMessage: false
  Smite:
    #Is smite just an effect, or is it real? (False = Effect)
    smiteDamage: false
  Teleport:
    #The delay until the teleport ask request is cancelled in seconds
    TpaCancel: 30
    #Enable delay?
    EnableDelay: false
    #The delay. (In seconds)
    Delay: 5
  Spawn:
    #Set this to 'lowest', if you want the world (or multiverse) to handle the respawning.
    #Set this to 'high', if you want UltimateCore to handle the respawning.
    #Set this to 'highest', if you want to force UltimateCore to handle the respawning.
    Priority: high
    #When there is a world spawn and a global group spawn set, which spawn must UC choose?
    # "world" or "group"
    WorldOrGroup: world
